declare const classNames: {
  readonly surfaceColor: 'surfaceColor'
  readonly surfaceColorDarker: 'surfaceColorDarker'
  readonly surfaceColorDarkest: 'surfaceColorDarkest'
  readonly focusRingColor: 'focusRingColor'
  readonly textColor: 'textColor'
  readonly fontFamily: 'fontFamily'
  readonly fontSizeBase: 'fontSizeBase'
  readonly fontWeightRegular: 'fontWeightRegular'
  readonly fontWeightMedium: 'fontWeightMedium'
  readonly h1FontSize: 'h1FontSize'
  readonly h2FontSize: 'h2FontSize'
  readonly h1FontWeight: 'h1FontWeight'
  readonly h2FontWeight: 'h2FontWeight'
  readonly borderRadius: 'borderRadius'
  readonly iconButtonTextColor: 'iconButtonTextColor'
  readonly wrapper: 'wrapper'
  readonly svg: 'svg'
  readonly displayValue: 'displayValue'
  readonly track: 'track'
  readonly progress: 'progress'
  readonly thumb: 'thumb'
}
export = classNames
